don't allow 'in' as variable/argument name, it causes confusing parse errors related to syntax restrictions for the 'in' operator
fail tests can now use '//#X message' to test whether an error message occurs X times in the log

svn path=/webdsls/trunk/; revision=4098

diff --git a/test/run-test-fail.sh.in b/test/run-test-fail.sh.in
--- a/test/run-test-fail.sh.in
+++ b/test/run-test-fail.sh.in
@@ -13,19 +13,33 @@ do
     pattern=`echo "$line" | sed 's/^[/]*//'`
     echo $pattern | grep -q "^\^"
     negate=$?
-    
-    if (( ! $negate )); then
+    echo $pattern | grep -q "^#"
+    count=$?
+    if [[ $negate == 0 ]]; then
+      echo "error must not be shown"
       if grep -q "${pattern:1}" $FILE.out; then
         echo "Error should not be present: ${pattern:1}"
         is_error=1
       fi
+    elif [[ $count == 0 ]]; then
+      echo "error must be shown X times"
+      occurrences=`echo $pattern | sed -E 's/^#([0-9]+) .*$/\1/'`
+      echo "X = $occurrences"
+      pattern=`echo $pattern | sed -E 's/^#[0-9]+ (.*)$/\1/'`
+      echo "error = $pattern"
+      foundlines=`grep "$pattern" $FILE.out | wc -l`
+      echo "found X = $foundlines"
+      if [ $foundlines -ne $occurrences ]; then
+        echo "Error should be reported $occurrences times: $pattern"
+        is_error=1
+      fi      
     else
+      echo "error must be shown"
       if ! grep -q "$pattern" $FILE.out; then
         echo "Error should be present: $pattern"
         is_error=1
       fi
     fi
-    
   else
     break
   fi
