start tomcat and deploy war file from java code
svn path=/webdsls/trunk/; revision=3031

diff --git a/src/org/webdsl/dsl/project/webdsl.in b/src/org/webdsl/dsl/project/webdsl.in
--- a/src/org/webdsl/dsl/project/webdsl.in
+++ b/src/org/webdsl/dsl/project/webdsl.in
@@ -476,6 +476,20 @@ function check_app {
   return $RET
 }
 
+function check_web_app {
+  cd .servletapp
+  ant check-web
+  RET="$?"
+  cd ..
+  if [ "$RET" == 0 ]
+  then
+    echo "Check succesful."
+    return $RET
+  fi
+  echo "Check failed."
+  return $RET
+}
+
 function clean_app {
   echo "Removing servlet project files and dist directory."
   rm -rf $SERVLETPROJECTDIR
@@ -673,8 +687,14 @@ for i in $commands; do
        fi
        ;;
     "check" )
+       clean_app
        make_app
        check_app
+       ;;
+    "check-web" )
+       clean_app
+       make_app
+       check_web_app
        ;;
     "convert-to-unicode" )
        load_config
